### ISSUE TITLE
vim8 fails to work

### ISSUE THREAD

**Issue by liuchengxu** [roxma/nvim-completion-manager#51]
nvim.log_py3_cm_core:
```
2017-03-12 21:24:10,739 [INFO @ cm_start.py:start_channel:54] 66464 - start_channel for cm_core
2017-03-12 21:24:10,739 [INFO @ cm_start.py:setup_neovim:103] 66464 - connecting to neovim server: 127.0.0.1:52413
2017-03-12 21:24:10,758 [INFO @ session.py:request:97] 66464 - 'Received error: [1, b'vim_eval not implemented']
2017-03-12 21:24:10,758 [ERROR @ cm_start.py:start_channel:95] 66464 - Exception when running cm_core: b'vim_eval not implemented'
Traceback (most recent call last):
  File "/Users/xlc/.vim/plugged/nvim-completion-manager/pythonx/cm_start.py", line 66, in start_channel
    nvim = setup_neovim(serveraddr)
  File "/Users/xlc/.vim/plugged/nvim-completion-manager/pythonx/cm_start.py", line 113, in setup_neovim
    pythonxs = nvim.eval('globpath(&rtp,"pythonx",1)')
  File "/Users/xlc/anaconda3/lib/python3.5/site-packages/neovim/api/nvim.py", line 224, in eval
    return self.request('vim_eval', string, **kwargs)
  File "/Users/xlc/anaconda3/lib/python3.5/site-packages/neovim/api/nvim.py", line 129, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/xlc/anaconda3/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'vim_eval not implemented'
```

nvim.log_py3_neovim_rpc_server:
```
2017-03-12 21:24:10,540 [INFO @ neovim_rpc_server.py:handle:86] 66462 - === socket opened ===
2017-03-12 21:24:10,541 [INFO @ neovim_rpc_server.py:handle:100] 66462 - received: b'[1,"neovim_rpc_setup"]\n'
2017-03-12 21:24:10,541 [INFO @ neovim_rpc_server.py:handle:115] 66462 - sending ["ex", "scall neovim_rpc#_callback()"]
2017-03-12 21:24:10,741 [INFO @ neovim_rpc_server.py:handle:141] 66462 - === socket opened for client ===
2017-03-12 21:24:10,741 [INFO @ neovim_rpc_server.py:handle:152] 66462 - unpacked: [0, 1, b'vim_get_api_info', []]
2017-03-12 21:24:10,741 [INFO @ neovim_rpc_server.py:notify:71] 66462 - sending notification: ["ex", "call neovim_rpc#_callback()"]
2017-03-12 21:24:10,742 [INFO @ neovim_rpc_server.py:process_pending_requests:247] 66462 - process_pending_requests
2017-03-12 21:24:10,742 [INFO @ neovim_rpc_server.py:process_pending_requests:259] 66462 - get msg from channel [1]: [0, 1, 'vim_get_api_info', []]
2017-03-12 21:24:10,742 [INFO @ neovim_rpc_server.py:process_pending_requests:293] 66462 - sending result: [1, 1, None, [1, {'error_types': {'Validation': {'id': 1}, 'Exception': {'id': 0}}, 'functions': [{'return_type': 'Integer', 'method': True, 'since': 1, 'name': 'nvim_buf_line_count', 'parameters': [['Buffer', 'buffer']]}, {'method': False, 'name': 'buffer_get_line', 'parameters': [['Buffer', 'buffer'], ['Integer', 'index']], 'return_type': 'String', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'buffer_set_line', 'parameters': [['Buffer', 'buffer'], ['Integer', 'index'], ['String', 'line']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'buffer_del_line', 'parameters': [['Buffer', 'buffer'], ['Integer', 'index']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'buffer_get_line_slice', 'parameters': [['Buffer', 'buffer'], ['Integer', 'start'], ['Integer', 'end'], ['Boolean', 'include_start'], ['Boolean', 'include_end']], 'return_type': 'ArrayOf(String)', 'deprecated_since': 1, 'since': 0}, {'return_type': 'ArrayOf(String)', 'method': True, 'since': 1, 'name': 'nvim_buf_get_lines', 'parameters': [['Buffer', 'buffer'], ['Integer', 'start'], ['Integer', 'end'], ['Boolean', 'strict_indexing']]}, {'method': False, 'name': 'buffer_set_line_slice', 'parameters': [['Buffer', 'buffer'], ['Integer', 'start'], ['Integer', 'end'], ['Boolean', 'include_start'], ['Boolean', 'include_end'], ['ArrayOf(String)', 'replacement']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'return_type': 'void', 'method': True, 'since': 1, 'name': 'nvim_buf_set_lines', 'parameters': [['Buffer', 'buffer'], ['Integer', 'start'], ['Integer', 'end'], ['Boolean', 'strict_indexing'], ['ArrayOf(String)', 'replacement']]}, {'return_type': 'Object', 'method': True, 'since': 1, 'name': 'nvim_buf_get_var', 'parameters': [['Buffer', 'buffer'], ['String', 'name']]}, {'return_type': 'void', 'method': True, 'since': 1, 'name': 'nvim_buf_set_var', 'parameters': [['Buffer', 'buffer'], ['String', 'name'], ['Object', 'value']]}, {'return_type': 'void', 'method': True, 'since': 1, 'name': 'nvim_buf_del_var', 'parameters': [['Buffer', 'buffer'], ['String', 'name']]}, {'method': False, 'name': 'buffer_set_var', 'parameters': [['Buffer', 'buffer'], ['String', 'name'], ['Object', 'value']], 'return_type': 'Object', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'buffer_del_var', 'parameters': [['Buffer', 'buffer'], ['String', 'name']], 'return_type': 'Object', 'deprecated_since': 1, 'since': 0}, {'return_type': 'Object', 'method': True, 'since': 1, 'name': 'nvim_buf_get_option', 'parameters': [['Buffer', 'buffer'], ['String', 'name']]}, {'return_type': 'void', 'method': True, 'since': 1, 'name': 'nvim_buf_set_option', 'parameters': [['Buffer', 'buffer'], ['String', 'name'], ['Object', 'value']]}, {'return_type': 'Integer', 'method': True, 'since': 1, 'name': 'nvim_buf_get_number', 'parameters': [['Buffer', 'buffer']]}, {'return_type': 'String', 'method': True, 'since': 1, 'name': 'nvim_buf_get_name', 'parameters': [['Buffer', 'buffer']]}, {'return_type': 'void', 'method': True, 'since': 1, 'name': 'nvim_buf_set_name', 'parameters': [['Buffer', 'buffer'], ['String', 'name']]}, {'return_type': 'Boolean', 'method': True, 'since': 1, 'name': 'nvim_buf_is_valid', 'parameters': [['Buffer', 'buffer']]}, {'method': False, 'name': 'buffer_insert', 'parameters': [['Buffer', 'buffer'], ['Integer', 'lnum'], ['ArrayOf(String)', 'lines']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'return_type': 'ArrayOf(Integer, 2)', 'method': True, 'since': 1, 'name': 'nvim_buf_get_mark', 'parameters': [['Buffer', 'buffer'], ['String', 'name']]}, {'return_type': 'Integer', 'method': True, 'since': 1, 'name': 'nvim_buf_add_highlight', 'parameters': [['Buffer', 'buffer'], ['Integer', 'src_id'], ['String', 'hl_group'], ['Integer', 'line'], ['Integer', 'col_start'], ['Integer', 'col_end']]}, {'return_type': 'void', 'method': True, 'since': 1, 'name': 'nvim_buf_clear_highlight', 'parameters': [['Buffer', 'buffer'], ['Integer', 'src_id'], ['Integer', 'line_start'], ['Integer', 'line_end']]}, {'return_type': 'ArrayOf(Window)', 'method': True, 'since': 1, 'name': 'nvim_tabpage_list_wins', 'parameters': [['Tabpage', 'tabpage']]}, {'return_type': 'Object', 'method': True, 'since': 1, 'name': 'nvim_tabpage_get_var', 'parameters': [['Tabpage', 'tabpage'], ['String', 'name']]}, {'return_type': 'void', 'method': True, 'since': 1, 'name': 'nvim_tabpage_set_var', 'parameters': [['Tabpage', 'tabpage'], ['String', 'name'], ['Object', 'value']]}, {'return_type': 'void', 'method': True, 'since': 1, 'name': 'nvim_tabpage_del_var', 'parameters': [['Tabpage', 'tabpage'], ['String', 'name']]}, {'method': False, 'name': 'tabpage_set_var', 'parameters': [['Tabpage', 'tabpage'], ['String', 'name'], ['Object', 'value']], 'return_type': 'Object', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'tabpage_del_var', 'parameters': [['Tabpage', 'tabpage'], ['String', 'name']], 'return_type': 'Object', 'deprecated_since': 1, 'since': 0}, {'return_type': 'Window', 'method': True, 'since': 1, 'name': 'nvim_tabpage_get_win', 'parameters': [['Tabpage', 'tabpage']]}, {'return_type': 'Integer', 'method': True, 'since': 1, 'name': 'nvim_tabpage_get_number', 'parameters': [['Tabpage', 'tabpage']]}, {'return_type': 'Boolean', 'method': True, 'since': 1, 'name': 'nvim_tabpage_is_valid', 'parameters': [['Tabpage', 'tabpage']]}, {'return_type': 'void', 'method': False, 'since': 1, 'name': 'nvim_ui_attach', 'parameters': [['Integer', 'width'], ['Integer', 'height'], ['Dictionary', 'options']]}, {'method': False, 'name': 'ui_attach', 'parameters': [['Integer', 'width'], ['Integer', 'height'], ['Boolean', 'enable_rgb']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'return_type': 'void', 'method': False, 'since': 1, 'name': 'nvim_ui_detach', 'parameters': []}, {'return_type': 'void', 'method': False, 'since': 1, 'name': 'nvim_ui_try_resize', 'parameters': [['Integer', 'width'], ['Integer', 'height']]}, {'return_type': 'void', 'method': False, 'since': 1, 'name': 'nvim_ui_set_option', 'parameters': [['String', 'name'], ['Object', 'value']]}, {'return_type': 'void', 'method': False, 'since': 1, 'name': 'nvim_command', 'parameters': [['String', 'command']]}, {'return_type': 'void', 'method': False, 'since': 1, 'name': 'nvim_feedkeys', 'parameters': [['String', 'keys'], ['String', 'mode'], ['Boolean', 'escape_csi']]}, {'return_type': 'Integer', 'method': False, 'since': 1, 'name': 'nvim_input', 'parameters': [['String', 'keys']]}, {'return_type': 'String', 'method': False, 'since': 1, 'name': 'nvim_replace_termcodes', 'parameters': [['String', 'str'], ['Boolean', 'from_part'], ['Boolean', 'do_lt'], ['Boolean', 'special']]}, {'return_type': 'String', 'method': False, 'since': 1, 'name': 'nvim_command_output', 'parameters': [['String', 'str']]}, {'return_type': 'Object', 'method': False, 'since': 1, 'name': 'nvim_eval', 'parameters': [['String', 'expr']]}, {'return_type': 'Object', 'method': False, 'since': 1, 'name': 'nvim_call_function', 'parameters': [['String', 'fname'], ['Array', 'args']]}, {'return_type': 'Integer', 'method': False, 'since': 1, 'name': 'nvim_strwidth', 'parameters': [['String', 'str']]}, {'return_type': 'ArrayOf(String)', 'method': False, 'since': 1, 'name': 'nvim_list_runtime_paths', 'parameters': []}, {'return_type': 'void', 'method': False, 'since': 1, 'name': 'nvim_set_current_dir', 'parameters': [['String', 'dir']]}, {'return_type': 'String', 'method': False, 'since': 1, 'name': 'nvim_get_current_line', 'parameters': []}, {'return_type': 'void', 'method': False, 'since': 1, 'name': 'nvim_set_current_line', 'parameters': [['String', 'line']]}, {'return_type': 'void', 'method': False, 'since': 1, 'name': 'nvim_del_current_line', 'parameters': []}, {'return_type': 'Object', 'method': False, 'since': 1, 'name': 'nvim_get_var', 'parameters': [['String', 'name']]}, {'return_type': 'void', 'method': False, 'since': 1, 'name': 'nvim_set_var', 'parameters': [['String', 'name'], ['Object', 'value']]}, {'return_type': 'void', 'method': False, 'since': 1, 'name': 'nvim_del_var', 'parameters': [['String', 'name']]}, {'method': False, 'name': 'vim_set_var', 'parameters': [['String', 'name'], ['Object', 'value']], 'return_type': 'Object', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_del_var', 'parameters': [['String', 'name']], 'return_type': 'Object', 'deprecated_since': 1, 'since': 0}, {'return_type': 'Object', 'method': False, 'since': 1, 'name': 'nvim_get_vvar', 'parameters': [['String', 'name']]}, {'return_type': 'Object', 'method': False, 'since': 1, 'name': 'nvim_get_option', 'parameters': [['String', 'name']]}, {'return_type': 'void', 'method': False, 'since': 1, 'name': 'nvim_set_option', 'parameters': [['String', 'name'], ['Object', 'value']]}, {'return_type': 'void', 'method': False, 'since': 1, 'name': 'nvim_out_write', 'parameters': [['String', 'str']]}, {'return_type': 'void', 'method': False, 'since': 1, 'name': 'nvim_err_write', 'parameters': [['String', 'str']]}, {'return_type': 'void', 'method': False, 'since': 1, 'name': 'nvim_err_writeln', 'parameters': [['String', 'str']]}, {'return_type': 'ArrayOf(Buffer)', 'method': False, 'since': 1, 'name': 'nvim_list_bufs', 'parameters': []}, {'return_type': 'Buffer', 'method': False, 'since': 1, 'name': 'nvim_get_current_buf', 'parameters': []}, {'return_type': 'void', 'method': False, 'since': 1, 'name': 'nvim_set_current_buf', 'parameters': [['Buffer', 'buffer']]}, {'return_type': 'ArrayOf(Window)', 'method': False, 'since': 1, 'name': 'nvim_list_wins', 'parameters': []}, {'return_type': 'Window', 'method': False, 'since': 1, 'name': 'nvim_get_current_win', 'parameters': []}, {'return_type': 'void', 'method': False, 'since': 1, 'name': 'nvim_set_current_win', 'parameters': [['Window', 'window']]}, {'return_type': 'ArrayOf(Tabpage)', 'method': False, 'since': 1, 'name': 'nvim_list_tabpages', 'parameters': []}, {'return_type': 'Tabpage', 'method': False, 'since': 1, 'name': 'nvim_get_current_tabpage', 'parameters': []}, {'return_type': 'void', 'method': False, 'since': 1, 'name': 'nvim_set_current_tabpage', 'parameters': [['Tabpage', 'tabpage']]}, {'return_type': 'void', 'method': False, 'since': 1, 'name': 'nvim_subscribe', 'parameters': [['String', 'event']]}, {'return_type': 'void', 'method': False, 'since': 1, 'name': 'nvim_unsubscribe', 'parameters': [['String', 'event']]}, {'return_type': 'Integer', 'method': False, 'since': 1, 'name': 'nvim_get_color_by_name', 'parameters': [['String', 'name']]}, {'return_type': 'Dictionary', 'method': False, 'since': 1, 'name': 'nvim_get_color_map', 'parameters': []}, {'return_type': 'Array', 'method': False, 'since': 1, 'name': 'nvim_get_api_info', 'parameters': []}, {'return_type': 'Array', 'method': False, 'since': 1, 'name': 'nvim_call_atomic', 'parameters': [['Array', 'calls']]}, {'return_type': 'Buffer', 'method': True, 'since': 1, 'name': 'nvim_win_get_buf', 'parameters': [['Window', 'window']]}, {'return_type': 'ArrayOf(Integer, 2)', 'method': True, 'since': 1, 'name': 'nvim_win_get_cursor', 'parameters': [['Window', 'window']]}, {'return_type': 'void', 'method': True, 'since': 1, 'name': 'nvim_win_set_cursor', 'parameters': [['Window', 'window'], ['ArrayOf(Integer, 2)', 'pos']]}, {'return_type': 'Integer', 'method': True, 'since': 1, 'name': 'nvim_win_get_height', 'parameters': [['Window', 'window']]}, {'return_type': 'void', 'method': True, 'since': 1, 'name': 'nvim_win_set_height', 'parameters': [['Window', 'window'], ['Integer', 'height']]}, {'return_type': 'Integer', 'method': True, 'since': 1, 'name': 'nvim_win_get_width', 'parameters': [['Window', 'window']]}, {'return_type': 'void', 'method': True, 'since': 1, 'name': 'nvim_win_set_width', 'parameters': [['Window', 'window'], ['Integer', 'width']]}, {'return_type': 'Object', 'method': True, 'since': 1, 'name': 'nvim_win_get_var', 'parameters': [['Window', 'window'], ['String', 'name']]}, {'return_type': 'void', 'method': True, 'since': 1, 'name': 'nvim_win_set_var', 'parameters': [['Window', 'window'], ['String', 'name'], ['Object', 'value']]}, {'return_type': 'void', 'method': True, 'since': 1, 'name': 'nvim_win_del_var', 'parameters': [['Window', 'window'], ['String', 'name']]}, {'method': False, 'name': 'window_set_var', 'parameters': [['Window', 'window'], ['String', 'name'], ['Object', 'value']], 'return_type': 'Object', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'window_del_var', 'parameters': [['Window', 'window'], ['String', 'name']], 'return_type': 'Object', 'deprecated_since': 1, 'since': 0}, {'return_type': 'Object', 'method': True, 'since': 1, 'name': 'nvim_win_get_option', 'parameters': [['Window', 'window'], ['String', 'name']]}, {'return_type': 'void', 'method': True, 'since': 1, 'name': 'nvim_win_set_option', 'parameters': [['Window', 'window'], ['String', 'name'], ['Object', 'value']]}, {'return_type': 'ArrayOf(Integer, 2)', 'method': True, 'since': 1, 'name': 'nvim_win_get_position', 'parameters': [['Window', 'window']]}, {'return_type': 'Tabpage', 'method': True, 'since': 1, 'name': 'nvim_win_get_tabpage', 'parameters': [['Window', 'window']]}, {'return_type': 'Integer', 'method': True, 'since': 1, 'name': 'nvim_win_get_number', 'parameters': [['Window', 'window']]}, {'return_type': 'Boolean', 'method': True, 'since': 1, 'name': 'nvim_win_is_valid', 'parameters': [['Window', 'window']]}, {'method': True, 'name': 'buffer_line_count', 'parameters': [['Buffer', 'buffer']], 'return_type': 'Integer', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'buffer_get_lines', 'parameters': [['Buffer', 'buffer'], ['Integer', 'start'], ['Integer', 'end'], ['Boolean', 'strict_indexing']], 'return_type': 'ArrayOf(String)', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'buffer_set_lines', 'parameters': [['Buffer', 'buffer'], ['Integer', 'start'], ['Integer', 'end'], ['Boolean', 'strict_indexing'], ['ArrayOf(String)', 'replacement']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'buffer_get_var', 'parameters': [['Buffer', 'buffer'], ['String', 'name']], 'return_type': 'Object', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'buffer_get_option', 'parameters': [['Buffer', 'buffer'], ['String', 'name']], 'return_type': 'Object', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'buffer_set_option', 'parameters': [['Buffer', 'buffer'], ['String', 'name'], ['Object', 'value']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'buffer_get_number', 'parameters': [['Buffer', 'buffer']], 'return_type': 'Integer', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'buffer_get_name', 'parameters': [['Buffer', 'buffer']], 'return_type': 'String', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'buffer_set_name', 'parameters': [['Buffer', 'buffer'], ['String', 'name']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'buffer_is_valid', 'parameters': [['Buffer', 'buffer']], 'return_type': 'Boolean', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'buffer_get_mark', 'parameters': [['Buffer', 'buffer'], ['String', 'name']], 'return_type': 'ArrayOf(Integer, 2)', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'buffer_add_highlight', 'parameters': [['Buffer', 'buffer'], ['Integer', 'src_id'], ['String', 'hl_group'], ['Integer', 'line'], ['Integer', 'col_start'], ['Integer', 'col_end']], 'return_type': 'Integer', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'buffer_clear_highlight', 'parameters': [['Buffer', 'buffer'], ['Integer', 'src_id'], ['Integer', 'line_start'], ['Integer', 'line_end']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'tabpage_get_windows', 'parameters': [['Tabpage', 'tabpage']], 'return_type': 'ArrayOf(Window)', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'tabpage_get_var', 'parameters': [['Tabpage', 'tabpage'], ['String', 'name']], 'return_type': 'Object', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'tabpage_get_window', 'parameters': [['Tabpage', 'tabpage']], 'return_type': 'Window', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'tabpage_is_valid', 'parameters': [['Tabpage', 'tabpage']], 'return_type': 'Boolean', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'ui_detach', 'parameters': [], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'ui_try_resize', 'parameters': [['Integer', 'width'], ['Integer', 'height']], 'return_type': 'Object', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_command', 'parameters': [['String', 'command']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_feedkeys', 'parameters': [['String', 'keys'], ['String', 'mode'], ['Boolean', 'escape_csi']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_input', 'parameters': [['String', 'keys']], 'return_type': 'Integer', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_replace_termcodes', 'parameters': [['String', 'str'], ['Boolean', 'from_part'], ['Boolean', 'do_lt'], ['Boolean', 'special']], 'return_type': 'String', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_command_output', 'parameters': [['String', 'str']], 'return_type': 'String', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_eval', 'parameters': [['String', 'expr']], 'return_type': 'Object', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_call_function', 'parameters': [['String', 'fname'], ['Array', 'args']], 'return_type': 'Object', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_strwidth', 'parameters': [['String', 'str']], 'return_type': 'Integer', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_list_runtime_paths', 'parameters': [], 'return_type': 'ArrayOf(String)', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_change_directory', 'parameters': [['String', 'dir']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_get_current_line', 'parameters': [], 'return_type': 'String', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_set_current_line', 'parameters': [['String', 'line']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_del_current_line', 'parameters': [], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_get_var', 'parameters': [['String', 'name']], 'return_type': 'Object', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_get_vvar', 'parameters': [['String', 'name']], 'return_type': 'Object', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_get_option', 'parameters': [['String', 'name']], 'return_type': 'Object', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_set_option', 'parameters': [['String', 'name'], ['Object', 'value']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_out_write', 'parameters': [['String', 'str']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_err_write', 'parameters': [['String', 'str']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_report_error', 'parameters': [['String', 'str']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_get_buffers', 'parameters': [], 'return_type': 'ArrayOf(Buffer)', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_get_current_buffer', 'parameters': [], 'return_type': 'Buffer', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_set_current_buffer', 'parameters': [['Buffer', 'buffer']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_get_windows', 'parameters': [], 'return_type': 'ArrayOf(Window)', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_get_current_window', 'parameters': [], 'return_type': 'Window', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_set_current_window', 'parameters': [['Window', 'window']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_get_tabpages', 'parameters': [], 'return_type': 'ArrayOf(Tabpage)', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_get_current_tabpage', 'parameters': [], 'return_type': 'Tabpage', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_set_current_tabpage', 'parameters': [['Tabpage', 'tabpage']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_subscribe', 'parameters': [['String', 'event']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_unsubscribe', 'parameters': [['String', 'event']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_name_to_color', 'parameters': [['String', 'name']], 'return_type': 'Integer', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_get_color_map', 'parameters': [], 'return_type': 'Dictionary', 'deprecated_since': 1, 'since': 0}, {'method': False, 'name': 'vim_get_api_info', 'parameters': [], 'return_type': 'Array', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'window_get_buffer', 'parameters': [['Window', 'window']], 'return_type': 'Buffer', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'window_get_cursor', 'parameters': [['Window', 'window']], 'return_type': 'ArrayOf(Integer, 2)', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'window_set_cursor', 'parameters': [['Window', 'window'], ['ArrayOf(Integer, 2)', 'pos']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'window_get_height', 'parameters': [['Window', 'window']], 'return_type': 'Integer', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'window_set_height', 'parameters': [['Window', 'window'], ['Integer', 'height']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'window_get_width', 'parameters': [['Window', 'window']], 'return_type': 'Integer', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'window_set_width', 'parameters': [['Window', 'window'], ['Integer', 'width']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'window_get_var', 'parameters': [['Window', 'window'], ['String', 'name']], 'return_type': 'Object', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'window_get_option', 'parameters': [['Window', 'window'], ['String', 'name']], 'return_type': 'Object', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'window_set_option', 'parameters': [['Window', 'window'], ['String', 'name'], ['Object', 'value']], 'return_type': 'void', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'window_get_position', 'parameters': [['Window', 'window']], 'return_type': 'ArrayOf(Integer, 2)', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'window_get_tabpage', 'parameters': [['Window', 'window']], 'return_type': 'Tabpage', 'deprecated_since': 1, 'since': 0}, {'method': True, 'name': 'window_is_valid', 'parameters': [['Window', 'window']], 'return_type': 'Boolean', 'deprecated_since': 1, 'since': 0}], 'version': {'api_prerelease': False, 'api_compatible': 0, 'major': 0, 'api_level': 1, 'minor': 1, 'patch': 7}, 'types': {'Window': {'id': 1, 'prefix': 'nvim_win_'}, 'Buffer': {'id': 0, 'prefix': 'nvim_buf_'}, 'Tabpage': {'id': 2, 'prefix': 'nvim_tabpage_'}}}]]
2017-03-12 21:24:10,749 [INFO @ neovim_rpc_server.py:process_pending_requests:296] 66462 - sended
2017-03-12 21:24:10,756 [INFO @ neovim_rpc_server.py:handle:152] 66462 - unpacked: [0, 2, b'vim_eval', [b'globpath(&rtp,"pythonx",1)']]
2017-03-12 21:24:10,756 [INFO @ neovim_rpc_server.py:notify:71] 66462 - sending notification: ["ex", "call neovim_rpc#_callback()"]
2017-03-12 21:24:10,757 [INFO @ neovim_rpc_server.py:process_pending_requests:247] 66462 - process_pending_requests
2017-03-12 21:24:10,757 [INFO @ neovim_rpc_server.py:process_pending_requests:259] 66462 - get msg from channel [1]: [0, 2, 'vim_eval', ['globpath(&rtp,"pythonx",1)']]
2017-03-12 21:24:10,757 [ERROR @ neovim_rpc_server.py:_process_request:325] 66462 - method vim_eval not implemented
2017-03-12 21:24:10,757 [ERROR @ neovim_rpc_server.py:process_pending_requests:287] 66462 - process failed: vim_eval not implemented
Traceback (most recent call last):
  File "/Users/xlc/.vim/plugged/vim-hug-neovim-rpc/pythonx/neovim_rpc_server.py", line 285, in process_pending_requests
    result = _process_request(channel,method,args)
  File "/Users/xlc/.vim/plugged/vim-hug-neovim-rpc/pythonx/neovim_rpc_server.py", line 326, in _process_request
    raise Exception('%s not implemented' % method)
Exception: vim_eval not implemented
2017-03-12 21:24:10,757 [INFO @ neovim_rpc_server.py:process_pending_requests:293] 66462 - sending result: [1, 2, [1, 'vim_eval not implemented'], None]
2017-03-12 21:24:10,757 [INFO @ neovim_rpc_server.py:process_pending_requests:296] 66462 - sended
2017-03-12 21:24:10,765 [INFO @ neovim_rpc_server.py:handle:158] 66462 - channel 1 closed.
2017-03-12 21:24:21,041 [INFO @ neovim_rpc_server.py:stop:333] 66462 - stop begin
2017-03-12 21:24:21,288 [INFO @ neovim_rpc_server.py:handle:98] 66462 - === socket closed ===
```

Another question: It seems that nvim-completion-manager will result in a delay in exiting from vim, which is normal in neovim. The delay issue disappeared when nvim-completion-manager is diabled in vim.

**Comment by roxma** [comment]
It seems the neovim-python client is using an old version of the api.

What version of the neovim pip module you're using `(pip list | grep neovim)`? Try update it to the latest version, it is `neovim (0.1.13)` on my system.

> Another question: It seems that nvim-completion-manager will result in a delay in exiting from vim, which is normal in neovim. The delay issue disappeared when nvim-completion-manager is diabled in vim.

The vim-hug-neovim-rpc, activated by NCM,  has at least two threads listening on tcp port, one for communicating with vim via json rpc, one for communicating with neovim python client via msgpack rpc.

These threads need to be stopped before exit vim, even if they are python daemon thread, otherwise vim will hang. This is the main reason that causes the delay.  Currently I have no idea how to solve this issue.

**Comment by liuchengxu** [comment]
It works! Thanks.

Do I need to open another issue on the delay problem?

**Comment by roxma** [comment]
Feel free to open it. 

I may not be able to solve it, though.

**Comment by liuchengxu** [comment]
That's ok. You already did a good job.
