### ISSUE TITLE
How do I use this with Go projects?

### ISSUE THREAD

**Issue by daenney** [roxma/nvim-completion-manager#82]
I've been trying to get this to work (with Go projects) since someone recommended it to me but I just can't figure it out.

So far I have:

- Used dein to install the plugin: `call dein#add('roxma/nvim-completion-manager')`
- Added the LanguageServer support: `call dein#add('autozimu/LanguageClient-neovim')`

I figured I'd be all set at this point since the README claims having Go support on board through `gocode`. Navigated to one of my Go projects, opened them up, started typing and much is happening.

If I try something like `fmt.Fprintf` all I seem to get is suggestion for `Fprintf <Key>` and that's it. No further completion is suggested, like the call signature etc. Typing something like `fmt.` doesn't come up with any completions either.

**Comment by roxma** [comment]
- make sure the `gocode` could be found in your `$PATH` environment
- If still not working, I'll need [log files described in the trouble-shooting page](https://github.com/roxma/nvim-completion-manager/wiki/Trouble-shooting), minimal vimrc and detailed instructions on how to reproduce it.

**Comment by daenney** [comment]
I have no idea what happened but it works now. Have you tried turning it off and on again I guess.

For reference, my `init.vim` looks like this:

```
if &compatible
  set nocompatible
endif
let g:python_host_prog='/Users/daenney/.virtualenv/envs/neovim-python2/bin/python2'
let g:python3_host_prog='/Users/daenney/.virtualenv/envs/neovim-python3/bin/python3'

set runtimepath+=/Users/daenney/.local/share/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('/Users/daenney/.local/share/dein')
  call dein#begin('/Users/daenney/.local/share/dein')
  call dein#add('/Users/daenney/.local/share/dein/repos/github.com/Shougo/dein.vim')

  call dein#add('chriskempson/tomorrow-theme', { 'rtp': 'vim'})
  call dein#add('Shougo/denite.nvim')

  call dein#add('autozimu/LanguageClient-neovim', { 'hook_post_update': ':UpdateRemotePlugins' })
  call dein#add('roxma/nvim-completion-manager')
  call dein#add('w0rp/ale')

  call dein#end()
  call dein#save_state()
endif

colorscheme Tomorrow-Night-Bright
filetype plugin indent on
syntax enable
```

And the Go file I was trying it on was:

```go
package main

import "fmt"

func main() {
}
```

Simply trying to insert `fmt.` in the body of main didn't show up with any completion suggestions even though `gocode` was running, similarly with just trying `fmt.Fprin` to give it a bit more of a hint.

**Comment by xerron** [comment]
gocode work
gocode in the PATH

Ubuntu 16.04

nvim_log_cm_gocode:

```
Traceback (most recent call last):
  File "/home/xerron/.vim/plugged/nvim-completion-manager/pythonx/cm.py", line 264, in on_notification
    func(*args)
  File "/home/xerron/.vim/plugged/nvim-completion-manager/pythonx/cm_sources/cm_gocode.py", line 69, in cm_refresh
    stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'gocode'
2018-01-25 04:18:09,891 [DEBUG @ cm.py:on_notification:248] 21827 - channel method: cm_refresh, args: [{'enable': 1, 'abbreviation': 'Go', 'scoping': 1, 'sort': 1, 'auto_popup': 1, 'name': 'cm-gocode', 'cm_refresh_length': 3, 'early_cache': 1, 'cm_refresh_patterns': ['\\.'], 'priority': 9, 'scopes': ['go'], 'word_pattern': '[\\w/]+', 'channel': {'events': [], 'type': 'python3', 'module': 'cm_sources.cm_gocode', 'id': 6}}, {'bufnr': 1, 'match_end': 1, 'scope_match': 'go', 'force': 0, 'scope': 'go', 'early_cache': 0, 'curpos': [0, 18, 6, 0, 9], 'changedtick': 94, 'startcol': 2, 'base': 'time', 'filepath': '/home/xerron/Repo/go/src/github.com/xerron/hefesto/main.go', 'lnum': 18, 'col': 6, 'typed': '\ttime', 'filetype': 'go'}]
2018-01-25 04:18:09,903 [ERROR @ cm.py:on_notification:267] 21827 - Failed processing method: cm_refresh, args: [{'enable': 1, 'abbreviation': 'Go', 'scoping': 1, 'sort': 1, 'auto_popup': 1, 'name': 'cm-gocode', 'cm_refresh_length': 3, 'early_cache': 1, 'cm_refresh_patterns': ['\\.'], 'priority': 9, 'scopes': ['go'], 'word_pattern': '[\\w/]+', 'channel': {'events': [], 'type': 'python3', 'module': 'cm_sources.cm_gocode', 'id': 6}}, {'bufnr': 1, 'match_end': 1, 'scope_match': 'go', 'force': 0, 'scope': 'go', 'early_cache': 0, 'curpos': [0, 18, 6, 0, 9], 'changedtick': 94, 'startcol': 2, 'base': 'time', 'filepath': '/home/xerron/Repo/go/src/github.com/xerron/hefesto/main.go', 'lnum': 18, 'col': 6, 'typed': '\ttime', 'filetype': 'go'}]

```
