### ISSUE TITLE
setup_logging() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by fcying** [roxma/nvim-completion-manager#94]
I'm trying to use ncm in neovim, after I add ncm and open nvim, it broken. 

os:ubuntu x64
nvim 0.2.1

 reproduce ways
```
add Plug 'roxma/nvim-completion-manager' to init.vim
pip3 install --user neovim jedi mistune psutil setproctitle
nvim
```

broken message:
```
Error detected while processing function <SNR>75_on_core_channel_error:
line    1:
Traceback (most recent call last):^@  File "/home/jason/.vim/plugged/nvim-completion-manager/pythonx/cm_start.py", line 81, in <module>^@    main()^@  File "/home/jason/.vim/plugged/nvim-c
ompletion-manager/pythonx/cm_start.py", line 45, in main^@    setup_logging(modulename)^@TypeError: setup_logging() takes 0 positional arguments but 1 was given^@
Press ENTER or type command to continue
```

python3 pythonx/cm_start.py core  /tmp/nvim84KNeD/0
```
Traceback (most recent call last):
  File "pythonx/cm_start.py", line 81, in <module>
    main()
  File "pythonx/cm_start.py", line 45, in main
    setup_logging(modulename)
TypeError: setup_logging() takes 0 positional arguments but 1 was given

```

**Comment by roxma** [comment]
What about the output of these commands?

```
$ pip list | grep neovim
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
neovim (0.1.13)
```

```
$ python3
Python 3.6.1 (default, Jun  7 2017, 12:32:14) 
[GCC 6.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import neovim
>>> foo = neovim.setup_logging('foo')
>>>
```

**Comment by fcying** [comment]
```
pip list | grep neovim
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section)to disable this warning.
neovim (0.1.9)
```

```
python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import neovim
>>> foo = neovim.setup_logging('foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: setup_logging() takes 0 positional arguments but 1 was given
>>>

```

**Comment by roxma** [comment]
Try ```pip install --upgrade neovim```

**Comment by fcying** [comment]
it work now, nvim version is too low, tks~~
